version: '3.6'
services:
  <projectname>:
    privileged: true
    container_name: <projectname>
    image: <projectname>
    build:
     context: .
     dockerfile: Dockerfile
    volumes:
      - <host_path>:<docker_path>
    entrypoint: zsh
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            #device_ids: ['7']
            capabilities: [gpu]
    ports:
      - 8001:8000